Update pyproject comment about excluding pattern matching
Trying to run mypy with a Python version that doesn't support pattern
matching results in the following error:

```
mypy tests/test_pattern_matching.py
tests/test_pattern_matching.py:11:12: error: invalid syntax; you likely need to run mypy using Python 3.11 or newer  [syntax]
```