Specify type params for UnwrapError.result type
Mypy's strict mode complained about UnwrapError not specifying type
parameters for the Result instance (the .result attribute):

    $ mypy -- strict

    result/result.py: note: In member "__init__" of class "UnwrapError":
    result/result.py:257:32: error:
    Missing type parameters for generic type "Result" [type-arg]

    result/result.py: note: In member "result" of class "UnwrapError":
    result/result.py:262:25: error:
    Missing type parameters for generic type "Result"  [type-arg]

    Found 2 errors in 1 file (checked 3 source files)

Address this simply by making the implicit explicit, namely specifying
Any.

The alternative to make UnwrapError itself generic is not viable:
UnwrapError doesn't know about both ‘T’ and ‘E’, since it's raised from
Ok() or Err() which only know about either ‘T’ or ‘E’, never both.

In practice this is not a problem since inspecting UnwrapError is only
useful for debugging, not as a normal control flow for which type safety
matters. Catching exceptions for error handling quite literally goes
against the whole idea of this library after all.